CREATE TABLE "WM_USUARIO"(
    "ID" BIGINT NOT NULL,
    "USERNAME" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255) NOT NULL,
    "DATACADASTRO" DATETIME NOT NULL,
    "DATAALTERACAO" DATETIME NOT NULL
);
ALTER TABLE
    "WM_USUARIO" ADD CONSTRAINT "wm_usuario_id_primary" PRIMARY KEY("ID");
CREATE UNIQUE INDEX "wm_usuario_username_unique" ON
    "WM_USUARIO"("USERNAME");
CREATE TABLE "WM_CONTABANCARIA"(
    "ID" BIGINT NOT NULL,
    "USUARIO" BIGINT NOT NULL,
    "NUMERO" VARCHAR(255) NOT NULL,
    "BANCO" BIGINT NOT NULL,
    "DATACADASTRO" DATETIME NOT NULL,
    "DATAALTERACAO" DATETIME NOT NULL
);
ALTER TABLE
    "WM_CONTABANCARIA" ADD CONSTRAINT "wm_contabancaria_id_primary" PRIMARY KEY("ID");
CREATE TABLE "WM_BANCO"(
    "ID" BIGINT NOT NULL,
    "NOME" VARCHAR(255) NOT NULL,
    "DATAALTERACAO" DATETIME NOT NULL,
    "DATACADASTRO" DATETIME NOT NULL
);
ALTER TABLE
    "WM_BANCO" ADD CONSTRAINT "wm_banco_id_primary" PRIMARY KEY("ID");
CREATE TABLE "WM_CARTAO"(
    "ID" BIGINT NOT NULL,
    "APELIDO" BIGINT NOT NULL,
    "BANCO" BIGINT NOT NULL,
    "CARTAOCREDITO" BIGINT NOT NULL,
    "DATACADASTRO" DATETIME NOT NULL,
    "DATAALTERACAO" DATETIME NOT NULL,
    "DATAFECHAMENTO" DATETIME NOT NULL,
    "TIPO" BIGINT NOT NULL,
    "LIMITE" BIGINT NULL
);
ALTER TABLE
    "WM_CARTAO" ADD CONSTRAINT "wm_cartao_id_primary" PRIMARY KEY("ID");
CREATE TABLE "WM_TRANSACAO"(
    "ID" BIGINT NOT NULL,
    "DESCRICAO" VARCHAR(255) NOT NULL,
    "VALOR" FLOAT(53) NOT NULL,
    "DATAEFETIVACAO" DATETIME NOT NULL,
    "CONTABANCARIA" BIGINT NOT NULL,
    "DATACADASTRO" DATETIME NOT NULL,
    "DATAALTERACAO" DATETIME NOT NULL,
    "TIPO" BIGINT NOT NULL
);
ALTER TABLE
    "WM_TRANSACAO" ADD CONSTRAINT "wm_transacao_id_primary" PRIMARY KEY("ID");
CREATE TABLE "WM_TIPOTRANSACAO"(
    "ID" BIGINT NOT NULL,
    "NOME" VARCHAR(255) NOT NULL,
    "DATAALTERACAO" DATETIME NOT NULL,
    "DATACADASTRO" DATETIME NOT NULL
);
ALTER TABLE
    "WM_TIPOTRANSACAO" ADD CONSTRAINT "wm_tipotransacao_id_primary" PRIMARY KEY("ID");
CREATE TABLE "WM_FATURA"(
    "ID" BIGINT NOT NULL,
    "CARTAO" BIGINT NOT NULL,
    "MES" SMALLINT NOT NULL,
    "ANO" SMALLINT NOT NULL,
    "DATAALTERACAO" DATETIME NOT NULL,
    "DATACADASTRO" DATETIME NOT NULL
);
ALTER TABLE
    "WM_FATURA" ADD CONSTRAINT "wm_fatura_id_primary" PRIMARY KEY("ID");
ALTER TABLE
    "WM_USUARIO" ADD CONSTRAINT "wm_usuario_id_foreign" FOREIGN KEY("ID") REFERENCES "WM_CONTABANCARIA"("ID");
ALTER TABLE
    "WM_TRANSACAO" ADD CONSTRAINT "wm_transacao_tipo_foreign" FOREIGN KEY("TIPO") REFERENCES "WM_TIPOTRANSACAO"("ID");
ALTER TABLE
    "WM_CARTAO" ADD CONSTRAINT "wm_cartao_banco_foreign" FOREIGN KEY("BANCO") REFERENCES "WM_BANCO"("ID");
ALTER TABLE
    "WM_FATURA" ADD CONSTRAINT "wm_fatura_cartao_foreign" FOREIGN KEY("CARTAO") REFERENCES "WM_CARTAO"("ID");
ALTER TABLE
    "WM_TRANSACAO" ADD CONSTRAINT "wm_transacao_contabancaria_foreign" FOREIGN KEY("CONTABANCARIA") REFERENCES "WM_CONTABANCARIA"("ID");
ALTER TABLE
    "WM_CONTABANCARIA" ADD CONSTRAINT "wm_contabancaria_id_foreign" FOREIGN KEY("ID") REFERENCES "WM_CARTAO"("ID");
ALTER TABLE
    "WM_CONTABANCARIA" ADD CONSTRAINT "wm_contabancaria_banco_foreign" FOREIGN KEY("BANCO") REFERENCES "WM_BANCO"("ID");